import { Product, ProductVariant } from '../../../libs/types/product';
import { ProductCategory, ProductGender } from '../../../libs/enums/product.enum';

const variants: ProductVariant[] = [
	{
		_id: '100',
		productId: '101',
		size: 'S',
		color: 'BLACK',
		stockQuantity: 35,
		productPrice: 24.99,
		salePrice: 19.99,
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		_id: '101',
		productId: '101',
		size: 'S',
		color: 'BLACK',
		stockQuantity: 28,
		productPrice: 24.99,
		salePrice: 19.99,
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		_id: '102',
		productId: '101',
		size: 'M',
		color: 'BLACK',
		stockQuantity: 42,
		productPrice: 25.99,
		salePrice: 20.99,
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		_id: '103',
		productId: '101',
		size: 'M',
		color: 'BLACK',
		stockQuantity: 39,
		productPrice: 25.99,
		salePrice: 20.99,
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		_id: '104',
		productId: '101',
		size: 'M',
		color: 'BLUE',
		stockQuantity: 25,
		productPrice: 25.99,
		salePrice: 20.99,
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		_id: '105',
		productId: '101',
		size: 'L',
		color: 'BLACK',
		stockQuantity: 45,
		productPrice: 26.99,
		salePrice: 21.99,
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		_id: '106',
		productId: '101',
		size: 'L',
		color: 'BLACK',
		stockQuantity: 40,
		productPrice: 26.99,
		salePrice: 21.99,
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		_id: '107',
		productId: '101',
		size: 'L',
		color: 'BLACK',
		stockQuantity: 18,
		productPrice: 26.99,
		salePrice: 21.99,
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		_id: '108',
		productId: '101',
		size: 'XL',
		color: 'BLACK',
		stockQuantity: 30,
		productPrice: 27.99,
		salePrice: 22.99,
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		_id: '109',
		productId: '101',
		size: 'XL',
		color: 'BLACK',
		stockQuantity: 22,
		productPrice: 27.99,
		salePrice: 22.99,
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		_id: '110',
		productId: '101',
		size: 'XXL',
		color: 'BLACK',
		stockQuantity: 15,
		productPrice: 29.99,
		salePrice: 23.99,
		createdAt: new Date(),
		updatedAt: new Date(),
	},
];

export const chosenProduct: Product = {
	_id: '101',
	productName: 'Classic Cotton T-shirt',
	productCategory: ProductCategory.TOPS,
	productGender: ProductGender.MEN,
	productDesc:
		'Premium quality cotton t-shirt with a comfortable fit and durable construction. Perfect for everyday casual wear.',
	productImages: ['/img/t-shirt.jpg', '/img/t-shirt.jpg'],
	isFeatured: false,
	onSale: true,
	productVariants: variants,
	isActive: true,
	createdAt: new Date(),
	updatedAt: new Date(),
	productViews: 0,
	reviewsCount: 0,
	reviewsRating: 0,
};
